import Head from 'next/head';
import Todolist from '../components/page/todolist';

export default function Home() {
  return (
    <>
      <Head>
        <title>Todo-List App created by Basofi Ibnu</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Todolist />
    </>
  );
}
